services:
  backend:
    environment:
      OTEL_EXPORTER_PROTOCOL: ${OTEL_EXPORTER_PROTOCOL:-grpc}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-signoz-otel-collector:4317}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE:-true}
    networks:
      - vectorizer-app
      - signoz

networks:
  vectorizer-app:
    name: ${VECTORIZER_NETWORK_NAME:-vectorizer-app}
  signoz:
    external: true
    name: ${SIGNOZ_NETWORK_NAME:-signoz-net}
